<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" parallel="tests" data-provider-thread-count="4" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="2">
  <test thread-count="2" parallel="methods" name="ParallelExecution1(failed)" verbose="2">
    <classes>
      <class name="testcases.TC_Login_H008">
        <methods>
          <include name="logoutFromApp"/>
          <include name="setup"/>
          <include name="testValidLogin" invocation-numbers="1 0"/>
        </methods>
      </class> <!-- testcases.TC_Login_H008 -->
    </classes>
  </test> <!-- ParallelExecution1(failed) -->
  <test thread-count="2" parallel="methods" name="ParallelExecution2(failed)" verbose="2">
    <classes>
      <class name="testcases.TC_Login_H009">
        <methods>
          <include name="logoutFromApp"/>
          <include name="setup"/>
          <include name="testValidLogin" invocation-numbers="0 1"/>
        </methods>
      </class> <!-- testcases.TC_Login_H009 -->
    </classes>
  </test> <!-- ParallelExecution2(failed) -->
</suite> <!-- Failed suite [Suite] -->
